<!DOCTYPE TS>
<TS>
  <context>
    <name>slaeconv</name>
    <message>
      <source>700000/PLC/828D</source>
      <translation>机床急停,请检查急停按钮SB1状态！(I24/I2.7)</translation>
    </message>
    <message>
      <source>700001/PLC/828D</source>
      <translation>驱动器温度报警！(I33/I4.0)</translation>
    </message>
    <message>
      <source>700002/PLC/828D</source>
      <translation>驱动器未就绪！(I32/I3.7)</translation>
    </message>
    <message>
      <source>700003/PLC/828D</source>
      <translation>驱动器使能未加载,请加载使能！</translation>
    </message>
    <message>
      <source>700004/PLC/828D</source>
      <translation>DRF有效,正在手动干预X1状态,请注意！</translation>
    </message>
    <message>
      <source>700005/PLC/828D</source>
      <translation>DRF有效,正在手动干预X10状态,请注意！</translation>
    </message>
    <message>
      <source>700006/PLC/828D</source>
      <translation>DRF有效,正在手动干预X100状态,请注意！</translation>
    </message>
    <message>
      <source>700007/PLC/828D</source>
      <translation>机床X、Z、C轴未回零，请进行回零操作！</translation>
    </message>
    <message>
      <source>700008/PLC/828D</source>
      <translation>机床倍率为零！</translation>
    </message>
    <message>
      <source>700009/PLC/828D</source>
      <translation>QF13_砂轮电机过载！(I27/I3.2)</translation>
    </message>
    <message>
      <source>700010/PLC/828D</source>
      <translation>ALARM2_主轴变频器报警！(I28/I3.3)</translation>
    </message>
    <message>
      <source>700011/PLC/828D</source>
      <translation>QF2_液压泵电机过载！(I11/I1.2)</translation>
    </message>
    <message>
      <source>700012/PLC/828D</source>
      <translation>QF1_间歇润滑泵电机过载！(I9/I1.0)</translation>
    </message>
    <message>
      <source>700013/PLC/828D</source>
      <translation>KP1_机床润滑油液位过低,请加油！(I10/I1.1)</translation>
    </message>
    <message>
      <source>700014/PLC/828D</source>
      <translation>QF6_水冷机电机过载！(I17/I2.0)</translation>
    </message>
    <message>
      <source>700015/PLC/828D</source>
      <translation>KP3_水冷装置冷却水液位过低,请加冷却水！(I18/I2.1)</translation>
    </message>
    <message>
      <source>700016/PLC/828D</source>
      <translation>QF3_冷却泵电机过载！(I13/I1.4)</translation>
    </message>
    <message>
      <source>700017/PLC/828D</source>
      <translation>QF4_冲洗泵电机过载！(I14/I1.5)</translation>
    </message>
    <message>
      <source>700018/PLC/828D</source>
      <translation>QF8_冷却液箱过载！(I21/I2.4)</translation>
    </message>
    <message>
      <source>700019/PLC/828D</source>
      <translation>KP4_冷却油箱冷却油液位过低,请加冷却油！(I22/I2.5)</translation>
    </message>
    <message>
      <source>700020/PLC/828D</source>
      <translation>QF9_直流稳压电源过载！(I25/I3.0)</translation>
    </message>
    <message>
      <source>700021/PLC/828D</source>
      <translation>QF10_控制变压器过载！(I26/I3.1)</translation>
    </message>
    <message>
      <source>700022/PLC/828D</source>
      <translation>QF15_系统驱动器电源过载！(I31/I3.6)</translation>
    </message>
    <message>
      <source>700023/PLC/828D</source>
      <translation>QF5_吸雾器电机过载！(I15/I1.6)</translation>
    </message>
    <message>
      <source>700024/PLC/828D</source>
      <translation>QF7_电箱空调过载！(I19/I2.2)</translation>
    </message>
    <message>
      <source>700025/PLC/828D</source>
      <translation>ALARM1_电箱空调未运行！(I20/I2.3)</translation>
    </message>
    <message>
      <source>700026/PLC/828D</source>
      <translation>机床气压过低,请检查气路！(I34/I4.1)</translation>
    </message>
    <message>
      <source>700027/PLC/828D</source>
      <translation>A轴夹紧装置处于松开状态！</translation>
    </message>
    <message>
      <source>700028/PLC/828D</source>
      <translation>砂轮平衡砂轮启停按钮-SB1有效！</translation>
    </message>
    <message>
      <source>700029/PLC/828D</source>
      <translation>砂轮主轴温度报警！(I24/I2.7)</translation>
    </message>
    <message>
      <source>700030/PLC/828D</source>
      <translation>QF14_滚轮电机驱动器过载！(I29/I3.4)</translation>
    </message>
    <message>
      <source>700031/PLC/828D</source>
      <translation>ALARM3_滚轮电机驱动器报警！(I30/I3.5)</translation>
    </message>
    <message>
      <source>700032/PLC/828D</source>
      <translation>ALARM4_机械手报警！(I45/I5.4)</translation>
    </message>
    <message>
      <source>700033/PLC/828D</source>
      <translation>请先在JOG方式下启动液压泵！</translation>
    </message>
    <message>
      <source>700034/PLC/828D</source>
      <translation>KP2_液压油压力太低！(I12/I1.3)</translation>
    </message>
    <message>
      <source>700035/PLC/828D</source>
      <translation> 防护门处于未锁定状态！</translation>
    </message>
    <message>
      <source>700040/PLC/828D</source>
      <translation>异步子程序1输出出错！</translation>
    </message>
    <message>
      <source>700069/PLC/828D</source>
      <translation>砂轮主轴或滚轮电机转速超出允许范围，经检查！</translation>
    </message>
    <message>
      <source>700074/PLC/828D</source>
      <translation>数据存贮正在进行中，请稍等片刻！</translation>
    </message>
  </context>
</TS>
