<!DOCTYPE TS>
<TS>
  <context>
    <name>slaeconv</name>
    <message>
      <source>700000/PLC/828D</source>
      <translation>机床急停,请检查SB1</translation>
    </message>
    <message>
      <source>700001/PLC/828D</source>
      <translation>砂轮电机过载</translation>
    </message>
    <message>
      <source>700002/PLC/828D</source>
      <translation>修整轮 液压泵 静压泵过载</translation>
    </message>
    <message>
      <source>700003/PLC/828D</source>
      <translation>修整轮 液压泵 静压泵过载</translation>
    </message>
    <message>
      <source>700004/PLC/828D</source>
      <translation>修整轮 液压泵 静压泵过载</translation>
    </message>
    <message>
      <source>700005/PLC/828D</source>
      <translation>间歇润滑泵 水冷机 空调过载</translation>
    </message>
    <message>
      <source>700006/PLC/828D</source>
      <translation>外磨冷却泵 内磨冷却泵 修整冷却泵过载</translation>
    </message>
    <message>
      <source>700007/PLC/828D</source>
      <translation>外磨冷却泵 内磨冷却泵 修整冷却泵过载</translation>
    </message>
    <message>
      <source>700008/PLC/828D</source>
      <translation>外磨冷却泵 内磨冷却泵 修整冷却泵过载</translation>
    </message>
    <message>
      <source>700009/PLC/828D</source>
      <translation>吸雾器 冷却箱过载</translation>
    </message>
    <message>
      <source>700010/PLC/828D</source>
      <translation>吸雾器 冷却箱过载</translation>
    </message>
    <message>
      <source>700011/PLC/828D</source>
      <translation>-AF2报警 外圆主轴过载</translation>
    </message>
    <message>
      <source>700012/PLC/828D</source>
      <translation>排屑器过载</translation>
    </message>
    <message>
      <source>700013/PLC/828D</source>
      <translation>静压油冷机过载</translation>
    </message>
    <message>
      <source>700014/PLC/828D</source>
      <translation>间歇润滑泵 水冷机 空调过载</translation>
    </message>
    <message>
      <source>700015/PLC/828D</source>
      <translation>主轴冷却泵过载</translation>
    </message>
    <message>
      <source>700016/PLC/828D</source>
      <translation>头架润滑泵过载</translation>
    </message>
    <message>
      <source>700017/PLC/828D</source>
      <translation>间歇润滑泵2过载</translation>
    </message>
    <message>
      <source>700018/PLC/828D</source>
      <translation>铣刀主轴过载</translation>
    </message>
    <message>
      <source>700019/PLC/828D</source>
      <translation>控制变压器过载</translation>
    </message>
    <message>
      <source>700020/PLC/828D</source>
      <translation>冲洗泵电机过载</translation>
    </message>
    <message>
      <source>700021/PLC/828D</source>
      <translation>-AF1报警 电主轴过载</translation>
    </message>
    <message>
      <source>700022/PLC/828D</source>
      <translation>驱动电源过载</translation>
    </message>
    <message>
      <source>700023/PLC/828D</source>
      <translation>电主轴气密封检测</translation>
    </message>
    <message>
      <source>700024/PLC/828D</source>
      <translation>电主轴气压过低报警</translation>
    </message>
    <message>
      <source>700025/PLC/828D</source>
      <translation>冷却油箱未开</translation>
    </message>
    <message>
      <source>700026/PLC/828D</source>
      <translation>砂轮变频器报警</translation>
    </message>
    <message>
      <source>700027/PLC/828D</source>
      <translation>电主轴温度报警</translation>
    </message>
    <message>
      <source>700028/PLC/828D</source>
      <translation>修整轮驱动报警</translation>
    </message>
    <message>
      <source>700029/PLC/828D</source>
      <translation>驱动器温度报警</translation>
    </message>
    <message>
      <source>700030/PLC/828D</source>
      <translation>驱动器未就绪</translation>
    </message>
    <message>
      <source>700031/PLC/828D</source>
      <translation>铣刀主轴报警</translation>
    </message>
    <message>
      <source>700032/PLC/828D</source>
      <translation>静压油冷机报警</translation>
    </message>
    <message>
      <source>700033/PLC/828D</source>
      <translation>水冷装置报警</translation>
    </message>
    <message>
      <source>700034/PLC/828D</source>
      <translation>冷却油箱报警</translation>
    </message>
    <message>
      <source>700035/PLC/828D</source>
      <translation>气压过低报警</translation>
    </message>
    <message>
      <source>700036/PLC/828D</source>
      <translation>气压过高报警</translation>
    </message>
    <message>
      <source>700037/PLC/828D</source>
      <translation>-AF1报警 电主轴过载</translation>
    </message>
    <message>
      <source>700038/PLC/828D</source>
      <translation>-AF2报警 外圆主轴过载</translation>
    </message>
    <message>
      <source>700039/PLC/828D</source>
      <translation>气压异常报警</translation>
    </message>
    <message>
      <source>700040/PLC/828D</source>
      <translation>异步子程序1输出出错</translation>
    </message>
    <message>
      <source>700041/PLC/828D</source>
      <translation>未检测到主轴冷却水!</translation>
    </message>
    <message>
      <source>700042/PLC/828D</source>
      <translation>未检测到电主轴油雾润滑!</translation>
    </message>
    <message>
      <source>700043/PLC/828D</source>
      <translation>未检测到头架润滑液!</translation>
    </message>
    <message>
      <source>700044/PLC/828D</source>
      <translation>液压压力不足</translation>
    </message>
    <message>
      <source>700045/PLC/828D</source>
      <translation>静压压力不足</translation>
    </message>
    <message>
      <source>700046/PLC/828D</source>
      <translation>间歇润滑泵液位过低,请加润滑液!</translation>
    </message>
    <message>
      <source>700047/PLC/828D</source>
      <translation>间歇润滑泵2液位过低,请加润滑液!</translation>
    </message>
    <message>
      <source>700048/PLC/828D</source>
      <translation>驱动器使能未加载,请加载使能!</translation>
    </message>
    <message>
      <source>700049/PLC/828D</source>
      <translation>请注意，当前倍率为“0”!</translation>
    </message>
    <message>
      <source>700050/PLC/828D</source>
      <translation>液压未启动，请按相应按键开启!</translation>
    </message>
    <message>
      <source>700051/PLC/828D</source>
      <translation>请启动润滑泵!</translation>
    </message>
    <message>
      <source>700052/PLC/828D</source>
      <translation>自动卡盘/尾架未开启!</translation>
    </message>
    <message>
      <source>700053/PLC/828D</source>
      <translation>注意,测头正在伸出!</translation>
    </message>
    <message>
      <source>700054/PLC/828D</source>
      <translation>A轴夹紧装置处于松开状态</translation>
    </message>
    <message>
      <source>700055/PLC/828D</source>
      <translation>安全门未关闭，不能启动程序!</translation>
    </message>
    <message>
      <source>700056/PLC/828D</source>
      <translation>砂轮未达到设定转速!</translation>
    </message>
    <message>
      <source>700057/PLC/828D</source>
      <translation>修整轮未达到设定转速!</translation>
    </message>
    <message>
      <source>700058/PLC/828D</source>
      <translation>摆缸修整未回起始位置!</translation>
    </message>
    <message>
      <source>700059/PLC/828D</source>
      <translation>砂轮动平衡正在进行中，请稍后!</translation>
    </message>
    <message>
      <source>700060/PLC/828D</source>
      <translation>DRF功能有效,正在手动干预X1状态,请小心使用手轮!</translation>
    </message>
    <message>
      <source>700061/PLC/828D</source>
      <translation>DRF功能有效,正在手动干预X10状态,请小心使用手轮!</translation>
    </message>
    <message>
      <source>700062/PLC/828D</source>
      <translation>DRF功能有效,正在手动干预X100状态,请小心使用手轮!</translation>
    </message>
    <message>
      <source>700063/PLC/828D</source>
      <translation>机床轴未回零，请进行回零操作!</translation>
    </message>
    <message>
      <source>700064/PLC/828D</source>
      <translation>砂轮平衡失败，请重新平衡砂轮!</translation>
    </message>
    <message>
      <source>700065/PLC/828D</source>
      <translation>电箱空调过载</translation>
    </message>
    <message>
      <source>700066/PLC/828D</source>
      <translation>电箱空调报警</translation>
    </message>
    <message>
      <source>700067/PLC/828D</source>
      <translation>磁性分离器过载</translation>
    </message>
    <message>
      <source>700068/PLC/828D</source>
      <translation></translation>
    </message>
    <message>
      <source>700069/PLC/828D</source>
      <translation>主轴1/2转速已达到额定极限转速，请检查砂轮线速度是否设置有误！</translation>
    </message>
    <message>
      <source>700070/PLC/828D</source>
      <translation></translation>
    </message>
    <message>
      <source>700071/PLC/828D</source>
      <translation>A轴夹紧压力不足</translation>
    </message>
  </context>
</TS>
